#!/bin/bash
R='\033[1;31m'
G='\033[1;32m'
Y='\033[1;33m'
B='\033[1;34m'
M='\033[1;35m'
C='\033[1;36m'
W='\033[1;37m'
Green='\033[32m'
Gren='\033[32m'
Grey='\033[90m'
printf "$Grey"
echo $(clear)
echo-e $W"_____________________________________________________________________"
echo-e " $W ___ $Gray _,.---,---.,_"
echo-e " $W | $Grey ,;~' '~;,"
echo-e " $W | $Grey ,; ;,"
echo-e $R" Front$W | $Grey ; $Grey ;$W ,---$R Supraorbital Foramen"
echo-e $R" Bone$W |$Grey ,' $W /'"
echo-e $W" |$Grey; $W /'$Grey ;,"
echo-e $W" |$Grey ; ; . .$W <-'$Grey ; |"
echo-e $W" |__ $Gray| ; ______ ______ ;$W<-----$R Coronal Suture"
echo-e $W" ___ $Gray| '/~" ~" . "~ "~\' |"
echo-e $W" | $Grey| ~ ,-~~~^~, | ,~^~~~-, ~ |"
echo-e $R" mandible versus maxilla,$W |$Gray | | }:{ |$W <------$R Orbit"
echo-e $R"Nasal and$W |$Gray | l / | \ ! |"
echo-e $R"Zygomatic$W |$Grey .~ (__,.--" .^. "--.,__) ~."
echo-e $R" Bones $W |$Grey| ----;' / | \ ;$W-<---------$R Infraorbital Foramen"
echo-e $W" |__$Gray \__. \/^\/ .__"
echo-e $W" ___$Grey V| \ / |V$W <---$R Mastoid Process"
echo-e $W" | $Gray | |T~\___!___!___/~T| |"
echo-e $W" |$Gray | | IIII_I_I_I_IIII | |"
echo-e $R" Mandible$W |$Gray | \ III I I I III,/ |"
echo-e $W" |$Grey \ ~~~~~~~~~~ "
echo-e $W" |$Gray -\ . .$W <-x----$R Mental Foramen"
echo-e $W" |__ $Gray -\. ^ ."
echo " ^~~~^~~~^"
echo-e $W" _________________________________________________________________"
echo-e $W" Created by @CesarHackGray"
echo-e $W" Usage:$G show options"
echo
